#pragma kernel MarchPrepared
#include "/Includes/BaseMarchPrepared.compute"

RWStructuredBuffer<Triangle> triangles;

//check for speed when having 5 times as many threads on z axis one for each triangle -> not better
[numthreads(WAFE_FRONT_SIZE, 1, 1)]
void MarchPrepared(uint3 id : SV_DispatchThreadID)
{
	uint threadXID = id.x;
	if (threadXID >= length)
		return;

	triangles[threadXID] = GetTriangleFromThreadId(id);
	
}
